apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: angel3/ai-powered-alerting-system:v1.0.0
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          env:
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: sender-email
            - name: NOTIFICATION_RECEIVER
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: notification-receiver
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: SLACK_SIGNING_SECRET
          ports:
            - containerPort: 5000
          startupProbe:
            httpGet:
              path: /startup
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
