# Use the official Grafana image as a base
FROM grafana/grafana:main-ubuntu

# Copy only the Grafana configuration file
COPY ./prometheus-grafana/grafana.ini /etc/grafana/grafana.ini

# Expose Grafana web port
EXPOSE 3000

# Use the default entry point for the Grafana image
CMD ["/run.sh"]
