# Use the official Grafana image as a base
FROM grafana/grafana:latest

# Copy custom configuration files if needed
COPY ./grafana/provisioning /etc/grafana/provisioning

# Expose Grafana web port
EXPOSE 3000

# Use the default entry point for the Grafana image
CMD ["/run.sh"]
