# prometheus.yml
global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds
scrape_configs:
  - job_name: 'my-python-app'
    static_configs:
      - targets: ['python-app:8000']
      