name: Docker Compose Vulnerability Scan

on:
  push:
    branches:
      - main
      - stage
      - test
      - development

jobs:
  trivy-scan:
    name: Scan Docker Compose images for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Compose app image
        run: docker-compose -f docker-compose.yml build python-app

      - name: Run Trivy in offline mode (cached DB) for python-app
        run: |
          trivy image --offline --cache-dir /path/to/trivy/cache python-app:latest

      - name: Build Docker Compose prometheus image
        run: docker-compose -f docker-compose.yml build prometheus

      - name: Run Trivy in offline mode (cached DB) for prometheus
        run: |
          trivy image --offline --cache-dir /path/to/trivy/cache prometheus:latest

      - name: Build Docker Compose grafana image
        run: docker-compose -f docker-compose.yml build grafana

      - name: Run Trivy in offline mode (cached DB) for grafana
        run: |
          trivy image --offline --cache-dir /path/to/trivy/cache grafana:latest
