name: Docker Build and Push to DockerHub

on:
  workflow_run:
    workflows: ["SonarCloud Analysis"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.head_branch == 'main' }}  # Ensure builds run only for the main branch

    steps:
      # ✅ Step 1: Check out the Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      # ✅ Step 3: Download Version Artifact
      - name: Download Version Artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: version
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 4: Load Version Tag
      - name: Load Version Tag
        run: |
          IMAGE_TAG=$(cat version.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # ✅ Step 5: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # ✅ Step 6: Build and Push Docker Images with Layer Caching
      - name: Build and Push All Services with Cache
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "Using TIMESTAMP: $TIMESTAMP"

          export TAG=$TIMESTAMP
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

          # Build and push with layer caching enabled
          docker compose build \
            --build-arg TAG=$TAG \
            --cache-from type=gha \
            --cache-to type=gha,mode=max
          docker compose push

          echo "Docker images built and pushed with tag: $TAG"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
