name: Docker Vulnerability Scan

on:
  workflow_run:
    workflows: ["Docker Build and Push to DockerHub"]  # Triggered after the Build and Push workflow
    types:
      - completed

jobs:
  scan:
    name: Scan Docker Images for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.58.2/trivy_0.58.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.58.2_Linux-64bit.deb

      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Pull and Scan Python App Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ai-powered-alerting-system:${{ env.TAG }}
          trivy image ${{ secrets.DOCKER_USERNAME }}/ai-powered-alerting-system:${{ env.TAG }}

      - name: Pull and Scan Prometheus Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
          trivy image ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}

      - name: Pull and Scan Grafana Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
          trivy image ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
