name: Docker Compose Vulnerability Scan

on:
  push:
    branches:
      - main
      - stage
      - test
      - development

jobs:
  trivy-scan:
    name: Scan Docker Compose images for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Compose app image
        run: docker-compose -f docker-compose.yml build python-app

      - name: Scan app image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: python-app:v1.0.0  # Image name defined in docker-compose.yml for 'app' service
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Docker Compose prometheus image
        run: docker-compose -f docker-compose.yml build prometheus

      - name: Scan prometheus image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: prometheus:latest  # Image name defined in docker-compose.yml for 'prometheus' service

      - name: Build Docker Compose grafana image
        run: docker-compose -f docker-compose.yml build grafana

      - name: Scan grafana image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: grafana:latest  # Image name defined in docker-compose.yml for 'grafana' service
