name: Docker Build and Push to DockerHub

on:
  workflow_run:
    workflows: ["AI-Powered Alerting System CI"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Docker Buildx for better caching and multi-arch support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      # ✅ Step 3: Log in to DockerHub using secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # ✅ Step 4: Download Version Tag from CI Workflow
      - name: Download Version Tag
        uses: actions/download-artifact@v4.1.8
        with:
          name: coverage-report

      # ✅ Step 5: Extract Version from .bumpversion.cfg
      - name: Extract Image Tag from Version
        run: |
          IMAGE_TAG=$(grep -oP '(?<=current_version = )\d+\.\d+\.\d+' .bumpversion.cfg)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # ✅ Step 6: Build and Push Docker Image with Version Tag
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./my_app
          file: ./my_app/Dockerfile.app
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-powered-alerting-system:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-powered-alerting-system:${{ env.IMAGE_TAG }}

      # ✅ Step 7: Confirm Image Pushed
      - name: Show Image Digest
        run: |
          echo "Docker Image Pushed with Tag: ${{ env.IMAGE_TAG }}"
