name: Docker Vulnerability Scan

on:
  workflow_run:
    workflows: ["Docker Build and Push to DockerHub"]
    types:
      - completed

jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Scan Docker Images for Vulnerabilities
    runs-on: ubuntu-latest
    env:
      TRIVY_CACHE_DIR: /home/runner/work/trivy-cache
      TMPDIR: /home/runner/work/tmp

    steps:
      - name: Prepare Space
        run: |
          mkdir -p $TRIVY_CACHE_DIR
          mkdir -p $TMPDIR
          echo "Expanded /tmp to $TMPDIR"

      - name: Download TAG Artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          name: tag
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_search: true
          repo: meleksabit/ai-powered-alerting-system
          workflow_conclusion: success

      - name: Load TAG
        run: |
          TAG=$(cat tag.txt)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.59.1_Linux-64bit.deb

      - name: Log in to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Pull and Scan Python App Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ai-powered-alerting-system:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --ignore-unfixed \
            ${{ secrets.DOCKER_USERNAME }}/ai-powered-alerting-system:${{ env.TAG }}
          docker system prune -af
          sudo rm -rf /tmp/*

      - name: Pull and Scan Prometheus Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --ignore-unfixed \
            ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
          docker system prune -af
          sudo rm -rf /tmp/*

      - name: Pull and Scan Grafana Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
          trivy image --severity HIGH,CRITICAL --ignore-unfixed \
            ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
          docker system prune -af
          sudo rm -rf /tmp/*
