name: Kubernetes Security Scan for Misconfigurations

on:
  pull_request:
  push:
    branches:
      - main
      - stage
      - test
      - development

jobs:
  kubescape-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write  # Required for Code Scanning

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Run Kubescape scan using the GitHub action and generate both SARIF and JSON
      - name: Run Kubescape scan
        uses: kubescape/github-action@main
        continue-on-error: true
        with:
          format: sarif
          outputFile: kubescape-report.sarif
          # Optional: You can uncomment and provide Kubescape Portal credentials if needed
          # account: ${{secrets.KUBESCAPE_ACCOUNT}}
          # accessKey: ${{secrets.KUBESCAPE_ACCESS_KEY}}
          # server: ${{ vars.KUBESCAPE_SERVER }}

      # Upload Kubescape scan results to GitHub Code Scanning (SARIF format)
      - name: Upload Kubescape scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kubescape-report.sarif

      # Run Kubescape scan again for JSON output and upload it as an artifact
      - name: Run Kubescape scan for JSON output
        run: |
          kubescape scan k8s/ framework nsa,mitre \
            --format json \
            --output kubescape-report.json \
            --fail-threshold critical \
            --verbose

      # Upload Kubescape JSON report as an artifact for further inspection
      - name: Upload Kubescape JSON Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-json-report
          path: kubescape-report.json
