---
name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  # ✅ Step 1: Run Super-Linter in check-only mode (does not fix issues)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Run Super-Linter (Check Only)
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DISABLE_ERRORS: true  # Disable errors to prevent failing the workflow

  # ✅ Step 2: Run Super-Linter in fix mode and commit changes
  fix-lint-issues:
    permissions:
      contents: write  # Allows writing fixed files
      statuses: write  # Allows updating PR status
      checks: write  # Allows updating PR checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      
      - name: Run Super-Linter (Fix Mode)
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          # ✅ Enable auto-fix for Shell, Python, YAML, and Markdown:
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_PYTHON_PYINK: true
          FIX_MARKDOWN: true
          DISABLE_ERRORS: true  # Disable errors to prevent failing the workflow
